package repository;

import model.Knight;
import model.Rank;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.File;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

class KnightRepositoryTest {

    private DatabaseManager dbManager;
    private KnightRepository repo;
    private String testDbUrl;

    @BeforeEach
    void setUp(@TempDir Path tempDir) {
        // Використовуємо тимчасовий файл для бази даних
        File tempDb = tempDir.resolve("test_knights.db").toFile();
        testDbUrl = "jdbc:sqlite:" + tempDb.getAbsolutePath();
        
        DatabaseManager.resetInstance();
        dbManager = DatabaseManager.getInstance(testDbUrl);
        repo = new KnightRepository(dbManager);
    }

    @AfterEach
    void tearDown() {
        DatabaseManager.resetInstance();
    }

    @Test
    void testSaveAndLoad() {
        // 1. Створюємо лицаря
        Knight k = new Knight("Arthur", "British", Rank.MASTER);

        // 2. Збереження
        repo.save(k); // Зберігає в БД і кешує
        
        assertTrue(k.getId() > 0, "ID should be generated by the database");

        // 3. Імітація перезапуску програми (створюємо новий репозиторій)
        KnightRepository newRepo = new KnightRepository(dbManager);
        
        // Завантажуємо дані з диска (БД)
        newRepo.loadData();

        // Шукаємо лицаря з ID який був згенерований
        Knight loadedKnight = newRepo.findById(k.getId());

        // 4. Перевірка
        assertNotNull(loadedKnight, "Лицар має завантажитись з файлу (не бути null)");
        assertEquals("Arthur", loadedKnight.getName(), "Ім'я завантаженого лицаря має збігатися");
    }

    @Test
    void testRemove() {
        Knight k = new Knight("Lancelot", "French", Rank.VETERAN);
        repo.save(k);
        
        int id = k.getId();
        assertNotNull(repo.findById(id));
        
        // Видаляємо
        repo.remove(id);
        
        // Перевіряємо що видалено
        assertNull(repo.findById(id));
        
        // Переконуємось що з бази теж видалено (рефрешимо)
        repo.reload();
        assertNull(repo.findById(id));
    }
    
    @Test
    void testFindAll() {
        repo.save(new Knight("Arthur", "British", Rank.MASTER));
        repo.save(new Knight("Lancelot", "French", Rank.VETERAN));
        
        assertEquals(2, repo.findAll().size());
    }
}