package repository;

import model.Knight;
import model.Rank;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.File;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

class KnightRepositoryTest {

    private DatabaseManager dbManager;
    private KnightRepository repo;
    private String testDbUrl;

    @BeforeEach
    void setUp(@TempDir Path tempDir) {
        
        File tempDb = tempDir.resolve("test_knights.db").toFile();
        testDbUrl = "jdbc:sqlite:" + tempDb.getAbsolutePath();
        
        DatabaseManager.resetInstance();
        dbManager = DatabaseManager.getInstance(testDbUrl);
        repo = new KnightRepository(dbManager);
    }

    @AfterEach
    void tearDown() {
        DatabaseManager.resetInstance();
    }

    @Test
    void testSaveAndLoad() {
        
        Knight k = new Knight("Arthur", "British", Rank.MASTER);

        repo.save(k); 
        
        assertTrue(k.getId() > 0, "ID should be generated by the database");

        KnightRepository newRepo = new KnightRepository(dbManager);

        newRepo.loadData();

        Knight loadedKnight = newRepo.findById(k.getId());

        assertNotNull(loadedKnight, "Лицар має завантажитись з файлу (не бути null)");
        assertEquals("Arthur", loadedKnight.getName(), "Ім'я завантаженого лицаря має збігатися");
    }

    @Test
    void testRemove() {
        Knight k = new Knight("Lancelot", "French", Rank.VETERAN);
        repo.save(k);
        
        int id = k.getId();
        assertNotNull(repo.findById(id));

        repo.remove(id);

        assertNull(repo.findById(id));

        repo.reload();
        assertNull(repo.findById(id));
    }
    
    @Test
    void testFindAll() {
        repo.save(new Knight("Arthur", "British", Rank.MASTER));
        repo.save(new Knight("Lancelot", "French", Rank.VETERAN));
        
        assertEquals(2, repo.findAll().size());
    }

    @Test
    void testSaveAndLoadWithEquipment() throws Exception {
        
        try (java.sql.Connection c = dbManager.getConnection();
             java.sql.Statement s = c.createStatement()) {
            s.execute("INSERT INTO equipment_catalog (type, name, weight, price, stat_value) VALUES ('Sword', 'Test Sword', 10.0, 100.0, 15)");
        }
        
        Knight k = new Knight("Gawain", "Green", Rank.NOVICE);
        
        model.equipment.Ammunition sword = new model.equipment.Sword("Test Sword", 10.0, 100.0, 15);
        sword.setCatalogId(1);
        k.equip(sword);
        
        repo.save(k);

        repo.saveData();

        KnightRepository newRepo = new KnightRepository(dbManager);
        newRepo.loadData();
        
        Knight loaded = newRepo.findById(k.getId());
        assertNotNull(loaded);
        assertEquals(1, loaded.getEquipment().size());
        assertEquals("Test Sword", loaded.getEquipment().get(0).getName());
    }

    @Test
    void testLoadAllEquipmentTypes() throws Exception {
        
        try (java.sql.Connection c = dbManager.getConnection();
             java.sql.Statement s = c.createStatement()) {
            
            String[] types = {"Sword", "Helmet", "Breastplate", "Greaves", "Axe", "Bow", "Knife", "Shield", "TwoHandedSword", "Mace", "Spear", "UnknownType"};
            for (int i = 0; i < types.length; i++) {
                s.execute("INSERT INTO equipment_catalog (id, type, name, weight, price, stat_value) VALUES (" + (i+10) + ", '" + types[i] + "', 'Test " + types[i] + "', 1.0, 1.0, 1)");
            }

            s.execute("INSERT INTO knights (id, name, orden, rank) VALUES (999, 'TestKnightAllEq', 'Test', 'MASTER')");

            for (int i = 0; i < types.length; i++) {
                s.execute("INSERT INTO knight_equipment (knight_id, catalog_id) VALUES (999, " + (i+10) + ")");
            }
        }
        
        KnightRepository newRepo = new KnightRepository(dbManager);
        newRepo.loadData();
        
        Knight loaded = newRepo.findById(999);
        assertNotNull(loaded);
        
        assertEquals(11, loaded.getEquipment().size());
    }
}